package com.xiongbeer.webveins.service.protocol.message;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProcessData.proto

import com.google.protobuf.CodedInputStream;

public final class ProcessDataProto {
  private ProcessDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProcessDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProcessData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 type = 1;</code>
     */
    int getType();

    /**
     * <code>int32 crcCode = 2;</code>
     */
    int getCrcCode();

    /**
     * <code>int32 length = 3;</code>
     */
    int getLength();

    /**
     * <code>int64 sessionId = 4;</code>
     */
    long getSessionId();

    /**
     * <code>.ProcessData.CrawlerStatus status = 5;</code>
     */
    int getStatusValue();
    /**
     * <code>.ProcessData.CrawlerStatus status = 5;</code>
     */
    ProcessDataProto.ProcessData.CrawlerStatus getStatus();

    /**
     * <code>string urlFilePath = 6;</code>
     */
    java.lang.String getUrlFilePath();
    /**
     * <code>string urlFilePath = 6;</code>
     */
    com.google.protobuf.ByteString
        getUrlFilePathBytes();

    /**
     * <code>string urlFileName = 7;</code>
     */
    java.lang.String getUrlFileName();
    /**
     * <code>string urlFileName = 7;</code>
     */
    com.google.protobuf.ByteString
        getUrlFileNameBytes();

    /**
     * <code>string command = 8;</code>
     */
    java.lang.String getCommand();
    /**
     * <code>string command = 8;</code>
     */
    com.google.protobuf.ByteString
        getCommandBytes();

    /**
     * <code>string commandReasult = 9;</code>
     */
    java.lang.String getCommandReasult();
    /**
     * <code>string commandReasult = 9;</code>
     */
    com.google.protobuf.ByteString
        getCommandReasultBytes();

    /**
     * <code>bytes attachment = 10;</code>
     */
    com.google.protobuf.ByteString getAttachment();
  }
  /**
   * Protobuf type {@code ProcessData}
   */
  public  static final class ProcessData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProcessData)
      ProcessDataOrBuilder {
    // Use ProcessData.newBuilder() to construct.
    private ProcessData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProcessData() {
      type_ = 0;
      crcCode_ = 0;
      length_ = 0;
      sessionId_ = 0L;
      status_ = 0;
      urlFilePath_ = "";
      urlFileName_ = "";
      command_ = "";
      commandReasult_ = "";
      attachment_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProcessData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 16: {

              crcCode_ = input.readInt32();
              break;
            }
            case 24: {

              length_ = input.readInt32();
              break;
            }
            case 32: {

              sessionId_ = input.readInt64();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              urlFilePath_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              urlFileName_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              command_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              commandReasult_ = s;
              break;
            }
            case 82: {

              attachment_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProcessDataProto.internal_static_ProcessData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProcessDataProto.internal_static_ProcessData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProcessDataProto.ProcessData.class, ProcessDataProto.ProcessData.Builder.class);
    }

    /**
     * Protobuf enum {@code ProcessData.CrawlerStatus}
     */
    public enum CrawlerStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NULL = 0;</code>
       */
      NULL(0),
      /**
       * <code>WAITING = 1;</code>
       */
      WAITING(1),
      /**
       * <code>RUNNING = 2;</code>
       */
      RUNNING(2),
      /**
       * <code>FINNISHED = 3;</code>
       */
      FINNISHED(3),
      /**
       * <code>READY = 4;</code>
       */
      READY(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NULL = 0;</code>
       */
      public static final int NULL_VALUE = 0;
      /**
       * <code>WAITING = 1;</code>
       */
      public static final int WAITING_VALUE = 1;
      /**
       * <code>RUNNING = 2;</code>
       */
      public static final int RUNNING_VALUE = 2;
      /**
       * <code>FINNISHED = 3;</code>
       */
      public static final int FINNISHED_VALUE = 3;
      /**
       * <code>READY = 4;</code>
       */
      public static final int READY_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CrawlerStatus valueOf(int value) {
        return forNumber(value);
      }

      public static CrawlerStatus forNumber(int value) {
        switch (value) {
          case 0: return NULL;
          case 1: return WAITING;
          case 2: return RUNNING;
          case 3: return FINNISHED;
          case 4: return READY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CrawlerStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CrawlerStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CrawlerStatus>() {
              public CrawlerStatus findValueByNumber(int number) {
                return CrawlerStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ProcessDataProto.ProcessData.getDescriptor().getEnumTypes().get(0);
      }

      private static final CrawlerStatus[] VALUES = values();

      public static CrawlerStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CrawlerStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ProcessData.CrawlerStatus)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int CRCCODE_FIELD_NUMBER = 2;
    private int crcCode_;
    /**
     * <code>int32 crcCode = 2;</code>
     */
    public int getCrcCode() {
      return crcCode_;
    }

    public static final int LENGTH_FIELD_NUMBER = 3;
    private int length_;
    /**
     * <code>int32 length = 3;</code>
     */
    public int getLength() {
      return length_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 4;
    private long sessionId_;
    /**
     * <code>int64 sessionId = 4;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }

    public static final int STATUS_FIELD_NUMBER = 5;
    private int status_;
    /**
     * <code>.ProcessData.CrawlerStatus status = 5;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.ProcessData.CrawlerStatus status = 5;</code>
     */
    public ProcessDataProto.ProcessData.CrawlerStatus getStatus() {
      ProcessDataProto.ProcessData.CrawlerStatus result = ProcessDataProto.ProcessData.CrawlerStatus.valueOf(status_);
      return result == null ? ProcessDataProto.ProcessData.CrawlerStatus.UNRECOGNIZED : result;
    }

    public static final int URLFILEPATH_FIELD_NUMBER = 6;
    private volatile java.lang.Object urlFilePath_;
    /**
     * <code>string urlFilePath = 6;</code>
     */
    public java.lang.String getUrlFilePath() {
      java.lang.Object ref = urlFilePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        urlFilePath_ = s;
        return s;
      }
    }
    /**
     * <code>string urlFilePath = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUrlFilePathBytes() {
      java.lang.Object ref = urlFilePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        urlFilePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URLFILENAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object urlFileName_;
    /**
     * <code>string urlFileName = 7;</code>
     */
    public java.lang.String getUrlFileName() {
      java.lang.Object ref = urlFileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        urlFileName_ = s;
        return s;
      }
    }
    /**
     * <code>string urlFileName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUrlFileNameBytes() {
      java.lang.Object ref = urlFileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        urlFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMAND_FIELD_NUMBER = 8;
    private volatile java.lang.Object command_;
    /**
     * <code>string command = 8;</code>
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        command_ = s;
        return s;
      }
    }
    /**
     * <code>string command = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMANDREASULT_FIELD_NUMBER = 9;
    private volatile java.lang.Object commandReasult_;
    /**
     * <code>string commandReasult = 9;</code>
     */
    public java.lang.String getCommandReasult() {
      java.lang.Object ref = commandReasult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandReasult_ = s;
        return s;
      }
    }
    /**
     * <code>string commandReasult = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCommandReasultBytes() {
      java.lang.Object ref = commandReasult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandReasult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACHMENT_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString attachment_;
    /**
     * <code>bytes attachment = 10;</code>
     */
    public com.google.protobuf.ByteString getAttachment() {
      return attachment_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (crcCode_ != 0) {
        output.writeInt32(2, crcCode_);
      }
      if (length_ != 0) {
        output.writeInt32(3, length_);
      }
      if (sessionId_ != 0L) {
        output.writeInt64(4, sessionId_);
      }
      if (status_ != ProcessDataProto.ProcessData.CrawlerStatus.NULL.getNumber()) {
        output.writeEnum(5, status_);
      }
      if (!getUrlFilePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, urlFilePath_);
      }
      if (!getUrlFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, urlFileName_);
      }
      if (!getCommandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, command_);
      }
      if (!getCommandReasultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, commandReasult_);
      }
      if (!attachment_.isEmpty()) {
        output.writeBytes(10, attachment_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (crcCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, crcCode_);
      }
      if (length_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, length_);
      }
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, sessionId_);
      }
      if (status_ != ProcessDataProto.ProcessData.CrawlerStatus.NULL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, status_);
      }
      if (!getUrlFilePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, urlFilePath_);
      }
      if (!getUrlFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, urlFileName_);
      }
      if (!getCommandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, command_);
      }
      if (!getCommandReasultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, commandReasult_);
      }
      if (!attachment_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, attachment_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProcessDataProto.ProcessData)) {
        return super.equals(obj);
      }
      ProcessDataProto.ProcessData other = (ProcessDataProto.ProcessData) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && (getCrcCode()
          == other.getCrcCode());
      result = result && (getLength()
          == other.getLength());
      result = result && (getSessionId()
          == other.getSessionId());
      result = result && status_ == other.status_;
      result = result && getUrlFilePath()
          .equals(other.getUrlFilePath());
      result = result && getUrlFileName()
          .equals(other.getUrlFileName());
      result = result && getCommand()
          .equals(other.getCommand());
      result = result && getCommandReasult()
          .equals(other.getCommandReasult());
      result = result && getAttachment()
          .equals(other.getAttachment());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + CRCCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCrcCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionId());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + URLFILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getUrlFilePath().hashCode();
      hash = (37 * hash) + URLFILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getUrlFileName().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand().hashCode();
      hash = (37 * hash) + COMMANDREASULT_FIELD_NUMBER;
      hash = (53 * hash) + getCommandReasult().hashCode();
      hash = (37 * hash) + ATTACHMENT_FIELD_NUMBER;
      hash = (53 * hash) + getAttachment().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProcessDataProto.ProcessData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(CodedInputStream.newInstance(data));
    }
    public static ProcessDataProto.ProcessData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(CodedInputStream.newInstance(data), extensionRegistry);
    }
    public static ProcessDataProto.ProcessData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProcessDataProto.ProcessData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProcessDataProto.ProcessData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProcessDataProto.ProcessData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProcessDataProto.ProcessData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProcessDataProto.ProcessData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProcessDataProto.ProcessData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProcessDataProto.ProcessData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProcessDataProto.ProcessData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProcessDataProto.ProcessData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProcessDataProto.ProcessData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProcessData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProcessData)
        ProcessDataProto.ProcessDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProcessDataProto.internal_static_ProcessData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProcessDataProto.internal_static_ProcessData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProcessDataProto.ProcessData.class, ProcessDataProto.ProcessData.Builder.class);
      }

      // Construct using ProcessDataProto.ProcessData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        crcCode_ = 0;

        length_ = 0;

        sessionId_ = 0L;

        status_ = 0;

        urlFilePath_ = "";

        urlFileName_ = "";

        command_ = "";

        commandReasult_ = "";

        attachment_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProcessDataProto.internal_static_ProcessData_descriptor;
      }

      public ProcessDataProto.ProcessData getDefaultInstanceForType() {
        return ProcessDataProto.ProcessData.getDefaultInstance();
      }

      public ProcessDataProto.ProcessData build() {
        ProcessDataProto.ProcessData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProcessDataProto.ProcessData buildPartial() {
        ProcessDataProto.ProcessData result = new ProcessDataProto.ProcessData(this);
        result.type_ = type_;
        result.crcCode_ = crcCode_;
        result.length_ = length_;
        result.sessionId_ = sessionId_;
        result.status_ = status_;
        result.urlFilePath_ = urlFilePath_;
        result.urlFileName_ = urlFileName_;
        result.command_ = command_;
        result.commandReasult_ = commandReasult_;
        result.attachment_ = attachment_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProcessDataProto.ProcessData) {
          return mergeFrom((ProcessDataProto.ProcessData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProcessDataProto.ProcessData other) {
        if (other == ProcessDataProto.ProcessData.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getCrcCode() != 0) {
          setCrcCode(other.getCrcCode());
        }
        if (other.getLength() != 0) {
          setLength(other.getLength());
        }
        if (other.getSessionId() != 0L) {
          setSessionId(other.getSessionId());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getUrlFilePath().isEmpty()) {
          urlFilePath_ = other.urlFilePath_;
          onChanged();
        }
        if (!other.getUrlFileName().isEmpty()) {
          urlFileName_ = other.urlFileName_;
          onChanged();
        }
        if (!other.getCommand().isEmpty()) {
          command_ = other.command_;
          onChanged();
        }
        if (!other.getCommandReasult().isEmpty()) {
          commandReasult_ = other.commandReasult_;
          onChanged();
        }
        if (other.getAttachment() != com.google.protobuf.ByteString.EMPTY) {
          setAttachment(other.getAttachment());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProcessDataProto.ProcessData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProcessDataProto.ProcessData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int crcCode_ ;
      /**
       * <code>int32 crcCode = 2;</code>
       */
      public int getCrcCode() {
        return crcCode_;
      }
      /**
       * <code>int32 crcCode = 2;</code>
       */
      public Builder setCrcCode(int value) {
        
        crcCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 crcCode = 2;</code>
       */
      public Builder clearCrcCode() {
        
        crcCode_ = 0;
        onChanged();
        return this;
      }

      private int length_ ;
      /**
       * <code>int32 length = 3;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <code>int32 length = 3;</code>
       */
      public Builder setLength(int value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 length = 3;</code>
       */
      public Builder clearLength() {
        
        length_ = 0;
        onChanged();
        return this;
      }

      private long sessionId_ ;
      /**
       * <code>int64 sessionId = 4;</code>
       */
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>int64 sessionId = 4;</code>
       */
      public Builder setSessionId(long value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sessionId = 4;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.ProcessData.CrawlerStatus status = 5;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.ProcessData.CrawlerStatus status = 5;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ProcessData.CrawlerStatus status = 5;</code>
       */
      public ProcessDataProto.ProcessData.CrawlerStatus getStatus() {
        ProcessDataProto.ProcessData.CrawlerStatus result = ProcessDataProto.ProcessData.CrawlerStatus.valueOf(status_);
        return result == null ? ProcessDataProto.ProcessData.CrawlerStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.ProcessData.CrawlerStatus status = 5;</code>
       */
      public Builder setStatus(ProcessDataProto.ProcessData.CrawlerStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ProcessData.CrawlerStatus status = 5;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object urlFilePath_ = "";
      /**
       * <code>string urlFilePath = 6;</code>
       */
      public java.lang.String getUrlFilePath() {
        java.lang.Object ref = urlFilePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          urlFilePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string urlFilePath = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUrlFilePathBytes() {
        java.lang.Object ref = urlFilePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          urlFilePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string urlFilePath = 6;</code>
       */
      public Builder setUrlFilePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        urlFilePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string urlFilePath = 6;</code>
       */
      public Builder clearUrlFilePath() {
        
        urlFilePath_ = getDefaultInstance().getUrlFilePath();
        onChanged();
        return this;
      }
      /**
       * <code>string urlFilePath = 6;</code>
       */
      public Builder setUrlFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        urlFilePath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object urlFileName_ = "";
      /**
       * <code>string urlFileName = 7;</code>
       */
      public java.lang.String getUrlFileName() {
        java.lang.Object ref = urlFileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          urlFileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string urlFileName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUrlFileNameBytes() {
        java.lang.Object ref = urlFileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          urlFileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string urlFileName = 7;</code>
       */
      public Builder setUrlFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        urlFileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string urlFileName = 7;</code>
       */
      public Builder clearUrlFileName() {
        
        urlFileName_ = getDefaultInstance().getUrlFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string urlFileName = 7;</code>
       */
      public Builder setUrlFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        urlFileName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object command_ = "";
      /**
       * <code>string command = 8;</code>
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          command_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string command = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string command = 8;</code>
       */
      public Builder setCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string command = 8;</code>
       */
      public Builder clearCommand() {
        
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      /**
       * <code>string command = 8;</code>
       */
      public Builder setCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        command_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object commandReasult_ = "";
      /**
       * <code>string commandReasult = 9;</code>
       */
      public java.lang.String getCommandReasult() {
        java.lang.Object ref = commandReasult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commandReasult_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string commandReasult = 9;</code>
       */
      public com.google.protobuf.ByteString
          getCommandReasultBytes() {
        java.lang.Object ref = commandReasult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commandReasult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string commandReasult = 9;</code>
       */
      public Builder setCommandReasult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commandReasult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string commandReasult = 9;</code>
       */
      public Builder clearCommandReasult() {
        
        commandReasult_ = getDefaultInstance().getCommandReasult();
        onChanged();
        return this;
      }
      /**
       * <code>string commandReasult = 9;</code>
       */
      public Builder setCommandReasultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commandReasult_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString attachment_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes attachment = 10;</code>
       */
      public com.google.protobuf.ByteString getAttachment() {
        return attachment_;
      }
      /**
       * <code>bytes attachment = 10;</code>
       */
      public Builder setAttachment(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        attachment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes attachment = 10;</code>
       */
      public Builder clearAttachment() {
        
        attachment_ = getDefaultInstance().getAttachment();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ProcessData)
    }

    // @@protoc_insertion_point(class_scope:ProcessData)
    private static final ProcessDataProto.ProcessData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProcessDataProto.ProcessData();
    }

    public static ProcessDataProto.ProcessData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProcessData>
        PARSER = new com.google.protobuf.AbstractParser<ProcessData>() {
      public ProcessData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProcessData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProcessData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProcessData> getParserForType() {
      return PARSER;
    }

    public ProcessDataProto.ProcessData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProcessData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProcessData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ProcessData.proto\"\261\002\n\013ProcessData\022\014\n\004t" +
      "ype\030\001 \001(\005\022\017\n\007crcCode\030\002 \001(\005\022\016\n\006length\030\003 \001" +
      "(\005\022\021\n\tsessionId\030\004 \001(\003\022*\n\006status\030\005 \001(\0162\032." +
      "ProcessData.CrawlerStatus\022\023\n\013urlFilePath" +
      "\030\006 \001(\t\022\023\n\013urlFileName\030\007 \001(\t\022\017\n\007command\030\010" +
      " \001(\t\022\026\n\016commandReasult\030\t \001(\t\022\022\n\nattachme" +
      "nt\030\n \001(\014\"M\n\rCrawlerStatus\022\010\n\004NULL\020\000\022\013\n\007W" +
      "AITING\020\001\022\013\n\007RUNNING\020\002\022\r\n\tFINNISHED\020\003\022\t\n\005" +
      "READY\020\004B\022B\020ProcessDataProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProcessData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProcessData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProcessData_descriptor,
        new java.lang.String[] { "Type", "CrcCode", "Length", "SessionId", "Status", "UrlFilePath", "UrlFileName", "Command", "CommandReasult", "Attachment", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
