# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProcessData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProcessData.proto',
  package='',
  serialized_pb=_b('\n\x11ProcessData.proto\"\xd3\x01\n\x0bProcessData\x12\x13\n\x0burlFilePath\x18\x01 \x01(\t\x12\x13\n\x0burlFileName\x18\x02 \x01(\t\x12)\n\x06status\x18\x03 \x01(\x0e\x32\x13.ProcessData.Status:\x04NULL\x12\x0f\n\x07\x63ommand\x18\x04 \x01(\t\x12\x16\n\x0e\x63ommandReasult\x18\x05 \x01(\t\"F\n\x06Status\x12\x08\n\x04NULL\x10\x00\x12\x0b\n\x07WAITING\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\r\n\tFINNISHED\x10\x03\x12\t\n\x05READY\x10\x04\x42\x12\x42\x10ProcessDataProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PROCESSDATA_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ProcessData.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NULL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WAITING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINNISHED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READY', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=163,
  serialized_end=233,
)
_sym_db.RegisterEnumDescriptor(_PROCESSDATA_STATUS)


_PROCESSDATA = _descriptor.Descriptor(
  name='ProcessData',
  full_name='ProcessData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='urlFilePath', full_name='ProcessData.urlFilePath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='urlFileName', full_name='ProcessData.urlFileName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='ProcessData.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='ProcessData.command', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commandReasult', full_name='ProcessData.commandReasult', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROCESSDATA_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=233,
)

_PROCESSDATA.fields_by_name['status'].enum_type = _PROCESSDATA_STATUS
_PROCESSDATA_STATUS.containing_type = _PROCESSDATA
DESCRIPTOR.message_types_by_name['ProcessData'] = _PROCESSDATA

ProcessData = _reflection.GeneratedProtocolMessageType('ProcessData', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSDATA,
  __module__ = 'ProcessData_pb2'
  # @@protoc_insertion_point(class_scope:ProcessData)
  ))
_sym_db.RegisterMessage(ProcessData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\020ProcessDataProto'))
# @@protoc_insertion_point(module_scope)
